#!/bin/bash
if [ -z $1 ]; then
  echo Usage: $0 NEX_FILE "[ARGS]"
  echo Compiles and runs a Go program described by a .nex file.
  exit 0
fi
dir=$(mktemp -d)
here=$(pwd)
f=$(basename $1)
cp -l $1 $dir/$f
cd $dir
nex < $f > go.go
rm $f
6g go.go
6l go.6
cd $here
shift
$dir/6.out $*
rm -rf $dir
